---
- name: Create teleport service (systemd).
  template:
    src: "teleport.service.j2"
    dest: "/etc/systemd/system/teleport.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed
  notify: restart teleport
